steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/microservices-academy/images-steve/backend-estudiantes',
        '-f',
        'backend-estudiantes/Dockerfile.prod',
        '--platform=linux/amd64',
        'backend-estudiantes',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/microservices-academy/images-steve/backend-estudiantes',
      ]
    options:
    loggin: CLOUD_LOGGING_ONLY
